version: "3.7"
services:
  web:
    image: ${CI_REGISTRY_IMAGE:-aaas}/${IMAGE:-web}:${SANITIZED_BRANCH:-latest}
    build:
      context: .
      dockerfile: ./docker/django/prod/Dockerfile.web
      args:
        UID: ${UID:-10600}
        GID: ${GID:-10600}
        UNAME: ${UNAME:-aaas}
    container_name: web2
    ports:
      - "8000:80"
    hostname: web
    volumes:
      - media_volume:/home/aaas/media
      - ./:/home/aaas
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres
      - redis
    networks:
      - aaas_net

  celery:
    image: ${CI_REGISTRY_IMAGE:-aaas}/${IMAGE:-celery}:${SANITIZED_BRANCH:-latest}
    build:
      context: .
      dockerfile: ./docker/django/prod/Dockerfile.celery
      args:
        UID: ${UID:-10600}
        GID: ${GID:-10600}
        UNAME: ${UNAME:-aaas}
    container_name: celery2
    hostname: web
    volumes:
      - media_volume:/home/aaas/media
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres
      - redis
    networks:
      - aaas_net

  postgres:
    image: docker.io/bitnami/postgresql:14 
    container_name: postgres2
    hostname: postgres
    volumes:
      - pg_data:/bitnami/postgresql
    env_file:
      - ${ENV_FILE}
    networks:
      - aaas_net

  redis:
    image: ${CI_REGISTRY_IMAGE:-aaas}/${IMAGE:-redis}:${SANITIZED_BRANCH:-latest}
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    container_name: redis2
    hostname: redis
    volumes:
      - redis_data:/data
    networks:
      - aaas_net
  
  flask:
    image: ${CI_REGISTRY_IMAGE:-aaas}/${IMAGE:-flask}:${SANITIZED_BRANCH:-latest}
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
      args:
        UID: ${UID:-10600}
        GID: ${GID:-10600}
        UNAME: ${UNAME:-aaas}
    container_name: flask2
    ports:
      - "5000:5000"
    hostname: flask

    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres
      - redis
    networks:
      - aaas_net

  chrome:
      image: selenium/standalone-chrome:latest
      hostname: chrome
      networks:
        - aaas_net
      privileged: true
      shm_size: 2g


networks:
  aaas_net:

volumes:
  pg_data:
  redis_data:
  media_volume:
