# Generated by Django 4.0.1 on 2022-11-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltemplate',
            name='download_file',
            field=models.FileField(null=True, upload_to='', verbose_name='templates'),
        ),
        migrations.CreateModel(
            name='DownloadSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_file', models.FileField(null=True, upload_to='', verbose_name='templates')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'DownloadSoftware',
            },
        ),
    ]
