# Generated by Django 3.2.7 on 2022-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('S', 'seller'), ('B', 'buyer')], default='S', max_length=1),
        ),
    ]
