# Generated by Django 3.2.7 on 2022-10-10 04:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('tiny_requests', models.IntegerField(default=0)),
                ('normal_requests', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ApiPackage',
            },
        ),
        migrations.CreateModel(
            name='ApiService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(default='', max_length=255)),
                ('website_url', models.CharField(max_length=5000)),
                ('api_domain_url', models.CharField(max_length=5000)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'approved'), ('R', 'rejected'), ('P', 'pending')], default='P', max_length=1)),
                ('last_approval_request_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ApiService',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('redirect_url', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('apipackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apipackage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=5000)),
                ('documentation', models.TextField()),
                ('request_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='P', max_length=6)),
                ('request_level', models.CharField(choices=[('tiny', 'tiny'), ('normal', 'normal')], max_length=10)),
                ('test_data', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apiservice')),
            ],
            options={
                'db_table': 'Endpoints',
            },
        ),
        migrations.CreateModel(
            name='ClientPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('tiny_requests_left', models.IntegerField(default=0)),
                ('normal_requests_left', models.IntegerField(default=0)),
                ('last_request_used', models.DateTimeField(auto_now=True)),
                ('reactivation', models.IntegerField(verbose_name=0)),
                ('apipackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apipackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ClientPackages',
            },
        ),
        migrations.AddField(
            model_name='apipackage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apiservice'),
        ),
    ]
