# Generated by Django 3.2.7 on 2023-01-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221223_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('template_text', models.TextField()),
            ],
            options={
                'db_table': 'BrochureTemplates',
            },
        ),
        migrations.AddField(
            model_name='marketingplatforms',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_type',
            field=models.CharField(choices=[('A', 'API'), ('L', 'Logo'), ('H', 'TEMPLATE'), ('D', 'Software')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo_type',
            field=models.CharField(choices=[('PORTAIT', 'PORTAIT'), ('LANDSCAPE', 'LANDSCAPE'), ('SQUARE', 'SQUARE')], default='SQUARE', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('A', 'API'), ('L', 'Logo'), ('H', 'TEMPLATE'), ('D', 'Software')], default='A', max_length=1),
        ),
        migrations.AlterModelTable(
            name='marketingplatforms',
            table='MarketingPlatforms',
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='brochure/')),
                ('marketed_on', models.ManyToManyField(to='core.MarketingPlatforms')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'Brochure',
            },
        ),
    ]
