# Generated by Django 3.2.7 on 2023-01-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230111_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='DribbleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('description', models.TextField()),
                ('brochure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brochure')),
            ],
            options={
                'db_table': 'DribbleProduct',
            },
        ),
    ]
