# Generated by Django 3.2.7 on 2023-01-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_brochure_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochure',
            name='marketed_on',
            field=models.ManyToManyField(blank=True, null=True, to='core.MarketingPlatforms'),
        ),
    ]
