# Generated by Django 3.2.7 on 2023-01-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_brochure_marketed_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brochure',
            name='marketed_on',
        ),
        migrations.RemoveField(
            model_name='dribbleproduct',
            name='brochure',
        ),
        migrations.AddField(
            model_name='dribbleproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketed_on',
            field=models.ManyToManyField(blank=True, to='core.MarketingPlatforms'),
        ),
    ]
