# Generated by Django 3.2.7 on 2023-01-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dribbleproduct_dribble_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dribbleproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='market/dribble/'),
        ),
    ]
