# Generated by Django 3.2.7 on 2023-01-15 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dribbleproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
