# Generated by Django 3.2.7 on 2023-01-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_feedback_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservice',
            name='technical_instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='apiservice',
            name='technology',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='downloadsoftware',
            name='technical_instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='downloadsoftware',
            name='technology',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='downloadsoftware',
            name='trail_version',
            field=models.FileField(null=True, upload_to='', verbose_name='software-trail'),
        ),
        migrations.AddField(
            model_name='htmltemplate',
            name='technical_instructions',
            field=models.TextField(default=''),
        ),
    ]
