# Generated by Django 3.2.7 on 2023-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230116_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='dribbleproduct',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'APPROVED')], default='A', max_length=1),
        ),
    ]
