# Generated by Django 3.2.7 on 2023-01-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_dribbleproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dribbleproduct',
            name='tags',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='dribbleproduct',
            name='dribble_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
