# Generated by Django 3.2.7 on 2023-01-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230119_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dribbleproduct',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'APPROVED')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='dribbleproduct',
            name='tags',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='dribbleproduct',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
