# Generated by Django 3.2.4 on 2023-04-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230416_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
    ]
