# Generated by Django 3.2.4 on 2023-04-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230417_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpackages',
            name='reactivation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientpackages',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
