# Generated by Django 3.2.4 on 2023-04-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230418_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpackages',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
