# Generated by Django 3.2.4 on 2023-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_clientpackages_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
