# Generated by Django 3.2.4 on 2023-04-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_thumbnail_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochure',
            name='primary_color',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='brochure',
            name='secondary_color',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
