# Generated by Django 3.2.4 on 2023-04-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20230429_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brochuretemplates',
            name='template_html_text',
        ),
        migrations.RemoveField(
            model_name='brochuretemplates',
            name='template_js_text',
        ),
        migrations.RemoveField(
            model_name='brochuretemplates',
            name='title',
        ),
        migrations.AddField(
            model_name='brochuretemplates',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='brochure-templates/'),
        ),
        migrations.AddField(
            model_name='brochuretemplates',
            name='primary_color',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='brochuretemplates',
            name='product_type',
            field=models.CharField(choices=[('A', 'API'), ('L', 'Logo'), ('H', 'TEMPLATE'), ('D', 'Software')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='brochuretemplates',
            name='secondary_color',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
