# Generated by Django 3.2.4 on 2023-04-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20230429_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
