# Generated by Django 3.2.4 on 2023-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_user_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpackages',
            name='is_feedback_given',
            field=models.BooleanField(default=False),
        ),
    ]
