# Generated by Django 3.2.4 on 2023-04-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_clientpackages_is_feedback_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_average',
            field=models.FloatField(default=0),
        ),
    ]
