# Generated by Django 3.2.4 on 2023-05-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coroloftproduct',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coroloftproduct',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dribbleproduct',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
