# Generated by Django 3.2.4 on 2023-07-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_productclick_productimpression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclick',
            name='datestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
