# Generated by Django 3.2.4 on 2023-07-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_productclick_datestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimpression',
            name='datestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
