# Generated by Django 3.2.4 on 2023-07-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_productimpression_datestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpackages',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
